### ISSUE TITLE
import/require not working

### ISSUE THREAD

**Issue by aaronshaf** [DanRuta/jsNet#33]
After `npm install jsnet`... tried:

```
const {
  Network,
  Layer,
  FCLayer,
  ConvLayer,
  PoolLayer,
  Filter,
  Neuron,
  NetMath,
  NetUtil
} = require('jsnet')

console.log(Layer)
```

```
import {
  Network,
  Layer,
  FCLayer,
  ConvLayer,
  PoolLayer,
  Filter,
  Neuron,
  NetMath,
  NetUtil
} from 'jsnet'

console.log(Layer)
```

Outputs undefined.

Any ideas?

**Comment by aaronshaf** [comment]
`window.addEventListener("jsNetWASMLoaded", () => { console.log("loaded!") })`

also not working.

**Comment by DanRuta** [comment]
Hi Aaron. Just installed it and copy+pasted the above into a script. Using nodejs, it prints out `[Function: FCLayer]`. The script I used contains exactly:

```
const {
  Network,
  Layer,
  FCLayer,
  ConvLayer,
  PoolLayer,
  Filter,
  Neuron,
  NetMath,
  NetUtil
} = require('jsnet')

console.log(Layer)
```

Though it hasn't yet updated itself with v3, you can try npm's runkit page to see if it works differently: https://runkit.com/embed/bo7xjzyie5q7 .

If it does, then perhaps there was an installation issue? Also, is anything else in your script, or is that snippet all there is?

Please let me know. I'll keep looking, in the meantime, and I'll let you know if I find anything.

**Comment by aaronshaf** [comment]
FWIW, I am using https://parceljs.org/ to bundle.

**Comment by aaronshaf** [comment]
(In other words, I'm not using node. I'm trying to run it in the browser.)

**Comment by DanRuta** [comment]
I see. I've not heard of that before. I've set it up, and I do see an empty object, when require()-ing jsNet, so I can only assume there's an incompatibility with how jsNet exports its classes, and how it gets bundled by parceljs.

One thing I can think of is that jsNet exports all its classes as, for example:
```typeof window=="undefined" && (exports.PoolLayer = PoolLayer)```

I'm going to guess that as window is actually defined when loading it in the browser, it just never binds the classes to the export object.

And I guess the bundling must have its own scope, or something, so that the classes are not globally accessible, as they would otherwise be.

Give me a sec, if this is the case, I'll push some changes, and maybe that will fix it.

**Comment by aaronshaf** [comment]
Thanks so much!

**Comment by DanRuta** [comment]
Ok, try installing v3.0.1. Just tried it myself and it worked.

Just a side note, if you're planning to use the WebAssembly version, you need to be able to serve the NetWASM.wasm file, which gets requested from the root domain (like `/NetWASM.wasm`). You can find it in ```node_modules/jsnet/dist/NetWASM.wasm```
