### ISSUE TITLE
How does one use the wasm version in node?

### ISSUE THREAD

**Issue by aaronshaf** [DanRuta/jsNet#34]

**Comment by DanRuta** [comment]
I realize this wasn't very well documented. Thanks for pointing that out, I've updated the README.


To answer your question, however, due to the NetWASM.wasm file being lazy loaded by the generated glue code, you need to wait for that to get loaded, before you can use the network.

I suppose there are multiple ways to handle this, including having a setTimeout function, but the best I've come up with so far is an event-like function, similar to the "jsNetWASMLoaded" event for the browsers.

You can try the following example:

```
"use strict"

const {Network, FCLayer} = require("./node_modules/jsnet/dist/jsNetWebAssembly.min.js")
const Module = require("./node_modules/jsnet/dist/NetWASM.js")

const xor = [
    {input: [0, 0], expected: [0]},
    {input: [0, 1], expected: [1]},
    {input: [1, 0], expected: [1]},
    {input: [1, 1], expected: [0]}
]

global.onWASMLoaded = () => {

    const net = new Network({
        Module: Module,
        layers: [new FCLayer(2), new FCLayer(3), new FCLayer(1)]
    })

    net.train(xor, {epochs: 1000, log: false}).then(() => {
        console.log("Forward 0,0: ", net.forward(xor[0].input))
        console.log("Forward 0,1: ", net.forward(xor[1].input))
        console.log("Forward 1,0: ", net.forward(xor[2].input))
        console.log("Forward 1,1: ", net.forward(xor[3].input))
    })
}
```

I added the global.onWASMLoaded to v3.0.3, if you're using the npm package.
